<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'TMDB\\' => array($baseDir . '/src', $baseDir . '/src'),
    'Curl\\' => array($vendorDir . '/php-curl-class/php-curl-class/src/Curl'),
);
